/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "var(--color-surface, #0b1326)",
        "surface-dim": "var(--color-surface-dim, #0b1326)",
        "surface-bright": "var(--color-surface-bright, #31394d)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #060e20)",
        "surface-container-low": "var(--color-surface-container-low, #131b2e)",
        "surface-container": "var(--color-surface-container, #171f33)",
        "surface-container-high": "var(--color-surface-container-high, #222a3d)",
        "surface-container-highest": "var(--color-surface-container-highest, #2d3449)",
        "on-surface": "var(--color-on-surface, #dae2fd)",
        "on-surface-variant": "var(--color-on-surface-variant, #c2c6d6)",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "outline": "var(--color-outline, #8c909f)",
        "outline-variant": "var(--color-outline-variant, #424754)",
        "surface-tint": "#adc6ff",
        "primary": "var(--color-primary, #adc6ff)",
        "on-primary": "var(--color-on-primary, #002e6a)",
        "primary-container": "var(--color-primary-container, #4d8eff)",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        "secondary": "var(--color-secondary, #c0c1ff)",
        "on-secondary": "#1000a9",
        "secondary-container": "var(--color-secondary-container, #3131c0)",
        "on-secondary-container": "var(--color-on-secondary-container, #b0b2ff)",
        "tertiary": "var(--color-tertiary, #ffb786)",
        "on-tertiary": "#502400",
        "tertiary-container": "var(--color-tertiary-container, #df7412)",
        "on-tertiary-container": "#461f00",
        "error": "var(--color-error, #ffb4ab)",
        "on-error": "#690005",
        "error-container": "var(--color-error-container, #93000a)",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#723600",
        "background": "var(--color-background, #0b1326)",
        "on-background": "var(--color-on-background, #dae2fd)",
        "surface-variant": "var(--color-surface-variant, #2d3449)"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "sans-serif"],
        display: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "'Fira Code'", "Consolas", "monospace"],
        "code-block": ["'JetBrains Mono'", "'Fira Code'", "Consolas", "monospace"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-block": ["14px", { lineHeight: "1.7", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    }
  },
  plugins: []
}
